print("Hola Mundo te digo 'Hola' ")
print(100 + 50)
print ("100 + 50")
print("Hola" + 'Alberto')
print("Me llamo \"Alberto\"")
print("Esta es una linea\nY esta es otra linea")
print("\tEsta es la tercera linea")
print('This isn\'t a number')
print('Este signo \\ es una barra invertida')
print("------------------------")
print("Tu nombre es " + input("Dime tu nombre: ") + " " + input("Dime tu apellido: "))